name: Bean Mirror CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create coverage report
        run: ./gradlew check
      - uses: codecov/codecov-action@v1
        with:
          files: bean-mirror-tests/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
