name: Upload Parser CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21 ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create coverage report
        run: ./gradlew check
      - uses: codecov/codecov-action@v4
        with:
          files: bean-mirror-tests/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          token: ${{ secrets.codecov_token }}
